version: "3"
services:
  scstore-app:
    image: scstore:1.0.0
    container_name: "scstore-app"
    environment:
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - GIN_MODE=release
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    ports:
      - "80:8080"